### ISSUE TITLE
Улучшение диалога ввода капчи

### ISSUE THREAD

**Issue by TheDrHax** [mosmetro-android/mosmetro-android#148]
Довольно много идей сегодня прислали так что лучше их в виде списка оформить.

* [x] Увеличить размер изображения (#146)
* [x] Диалог закрывается при нажатии за его пределами (#145)
* [x] Автоматически устанавливать фокус на поле ввода
    * [x] Скрывать клавиатуру при закрытии диалога
* [x] ~~Переключать раскладку клавиатуры на латиницу~~ **невозможно**
    * Сделать свою клавиатуру? Сложно...
    * [x] [Возможность набирать кириллицей](https://github.com/TheDrHax/mosmetro-android/issues/148#issuecomment-308651125)
* [x] ~~Добавить кнопку "Не беспокоить 10 мин."~~ Вынести настройку отключения диалога в сам диалог
* [x] Возможность ввода капчи прямо через уведомление (Android 7.0+)
* [x] Предоставить информацию, из какого приложения вообще этот диалог появился
* [x] Диалог сбрасывается при повороте экрана
* [x] Диалог сбрасывается при переключении между приложениями: Сворачивать диалог в уведомление?
    * Убрать `excludeFromRecents`
    * Определить, запущен диалог из фона или из DebugActivity (требуется #154)
    * Не запускать `finish()` из `onPause()` у диалога, запущенного из DebugActivity
    * Вызывать диалог из фона с `addFlags(Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS)`
    * Показывать уведомление при закрытии диалога, запущенного из фона
* [x] CaptchaRequest не использует альтернативные иконки уведомлений

**Comment by labdsf** [comment]
> Диалог закрывается при нажатии за его пределами

По-моему это удобно. Иногда Wi-Fi слишком часто пропадает, особенно когда подключается к проезжающим автобусам или поезд останавливается. Кнопка "не беспокоить 10 минут" по-моему перебор, слишком сложно. Может быть перемещать просто диалог в уведомления по нажатию снаружи с возможностью из уведомления открыть опять диалог?

**Comment by TheDrHax** [comment]
@labdsf Можно и так. Это просто список конкретных предложений, так что ещё нужно их обдумать. Я бы тоже не хотел таймер на 10 минут или что-то вроде того.

**Comment by TheDrHax** [comment]
Хорошая новость: У меня тоже появилась капча! Ну или не очень хорошая...

Суть в том, что отмена диалога по нажатию за его пределами — реально не очень удобно. Я случайно отменил ввод капчи четыре раза из четырёх, пока скроллил текст.

Вместо этого можно просто отключить автоматическое открытие диалога, сняв галочку в нём же. Если начнёт доставать частыми запросами, просто выключаем прямо на месте и не обращаем внимание. Потом открываем диалог из уведомлений и включаем обратно.

Перенос уже открывшегося диалога в уведомления не имеет особого смысла, так как через некоторое время у него закончится срок годности или Wi-Fi отвалится, из-за чего он просто пропадёт. А для отмены можно просто нажать ОК, не вводя ничего.

**Comment by alexeyknyshev** [comment]
Можно еще выставить чтобы клавиатура на поле ввода была циферная

25.05.2017 21:05 пользователь "Дмитрий Карих" <notifications@github.com>
написал:

**Comment by labdsf** [comment]
@alexeyknyshev Так там шестнадцатеричные цифры же.

**Comment by alexeyknyshev** [comment]
Точно, забудьте)

26.05.2017 3:16 пользователь "Alexander Krotov" <notifications@github.com>
написал:

**Comment by gpchelkin** [comment]
Про клавиатуру. Чаще (думаю, у многих) включена русская раскладка. И когда запрашивается капча, примерно треть времени (у меня так) уходит на смену раскладки на английскую. Предлагаю следующее: транслитерировать введенную капчу перед отправкой, т.е. чтобы можно было 6df7 вводить как 6дф7.

**Comment by TheDrHax** [comment]
@gpchelkin Отличная идея! Только не очень очевидная в плане использования. Хотя, думаю, можно просто примечание в том же диалоге сделать.

**Comment by substanceof** [comment]
> Сделать свою клавиатуру? Сложно...
"Свою клавиатуру", на мой взгляд, громко сказано. Можно просто разложить в окне ввода кнопки с возможными символами. И скрывать их, если на поле ввода попадает фокус.

**Comment by Evercond** [comment]
О том как мешает ненужная всплывающая капча и легко теряется нужная, поправьте меня, если я не прав, но по моему немешающим важным всплываниям место в шторке. Т.е. потребовалась капча, вместо стрелочек и буквы М в скобках появляется C, и вытянув шторку можно ввести капчу. 

Собственная клава на окошке по моему тоже тру, как было здесь уже отмечено, символы шестнадцатеричные, а два ряда по 8 клавиш, в размере окна ввода капчи это даже крупнее штатной клавиатуры.

И еще одно рац.предложение, добавить в настройки виджета с разовым фоновым подключением галочку "остановить после удачного подключения". И вот зачем:

Думаю многие согласятся что "автоматичность" при наличии капчи становится не всесторонней, но приложение от этого менее полезным не становится, только кому-то может показаться менее удобным. Лично я всю историю моего общения с приложением использовал лишь ручной режим, по схеме: спустился в метро, вытянул шторку, включил вайфай, клацнул виджет, подождал, ввел капчу, остановил авторизацию, юзаю интернет. Если ошибка: виджет, капча, остановка. 

Так что с нынешней версией из лишних движений есть остановка автологина (у меня почему-то всё равно автовозобновление при ошибке не пашет, но меня и не парит) все равно выходя из метро конечно вайфай отключаю, но лишнее на мой взгляд телодвижение. Есть также переключение раскладки, и есть проблема с про....далбыванием окошка капчи. Имхо, шторка для хранения оповещения о капче напрашивается.

И спасибо автору за отличную прогу, она как минимум 5 миллиграмм нервных клеток (это дохренища) мне сэкономила (хоть стало можно ожидая жену на станции успеть в уходящий поезд вайбеоовый мэсседж швырнуть) . Сейчас только обновился, посмотрю как дела в новой версии.

**Comment by Evercond** [comment]
Вот ведь как всегда, написал трактат, наткнулся на обновление, а в нем уже почти всё реализовано, или убрав галочку авто выдачи капчи и раньше она в шторке была, не знаю, не пробовал. Извиняюсь, за многословие, верхний комент можно удалить.

**Comment by uburuntu** [comment]
Есть идея как упростить это:
> Переключать раскладку клавиатуры на латиницу -- невозможно
Давай добавим частичный транслит!
Часто попадаются капчи с цифрами и одной буквой "а", к примеру. И такие капчи хочется заполнить с помощью кириллической клавиатуры.

Остается выбрать какое соотношение делать: по созвучию или по похожести.
Типа "х" писать за "x" или "h".

Что думаете? Добавить этап перед отправкой капчи несложно и практически ничего не стоит, зато доп фича. Могу даже пулреквест сам оформить.

**Comment by uburuntu** [comment]
Ахах, почитал чуть выше. Уже писали про это :0
Ну что тогда, мб сделать?

**Comment by labdsf** [comment]
@uburuntu Если сделаешь то уверен что @TheDrHax примет.

"x" в капче нет, в капче только 0123456789abcdef

Достаточно так: а -> a; б,в -> b; с -> c; д -> d; е -> e; ф -> f
